#!/usr/bin/env ruby

require "uri"

STDIN.each do |line|
  url = line.split.last
  uri = URI.parse(url)

  filename = case uri.hostname
  when "rubytapas-media.s3.amazonaws.com"
    uri
      .path[1..-1]
  when "embed-ssl.wistia.com"
    uri
      .query
      .split("&")
      .sort[1]
      .split("=")
      .last
      .sub(/^rubytapas-/, "")
      .sub(/^\d+-episode-/, "")
  else
    raise "Unknown hostname, don't know how to find filename in URL."
  end

  puts "url = \"#{url.chomp}\""
  puts "output = \"#{filename}\""
end
